[project]
name = "mmn16-20940"
version = "0.1.0"
description = "The codebase for assignment 16"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.124.2",
    "httpx>=0.28.1",
]
